### ISSUE TITLE
Support Resolutions other than 1920x1080

### ISSUE THREAD

**Issue by umutbalkan** [HakuSystems/EasyExtractUnitypackage#15]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the program window opens and only useable at 1920x1080.

**Describe the solution you'd like**
Window scales itself e.g
![gif](https://docs.godotengine.org/en/stable/_images/stretch_viewport_keep.gif)
**Additional context**

**Comment by HakuSystems** [comment]
Thank you for reporting this issue! 🎉  

With the release of **Version 2.0.6.5**, DPI scaling support has been added via the new `DpiDecorator`, which should improve the adaptability of the program to various resolutions and scaling factors. Additionally, the fixed window dimensions in `Dashboard.xaml` have been removed, allowing the UI to scale dynamically.  

Please update to the latest version and let us know if this resolves the problem for you. If we don’t hear back within a few days, we’ll assume the issue has been resolved and will close this thread. Of course, you’re always welcome to reopen it or create a new issue if needed.

[Version 2.0.6.5](https://github.com/HakuSystems/EasyExtractUnitypackage/releases/tag/V2.0.6.5)

**Comment by HakuSystems** [comment]
**I've Improved the Feature a little bit more, now everything should work fine.**
Please update to the latest version and let us know if this resolves the problem for you. If we don’t hear back within a few days, we’ll assume the issue has been resolved and will close this thread. Of course, you’re always welcome to reopen it or create a new issue if needed.
[Version 2.0.6.6](https://github.com/HakuSystems/EasyExtractUnitypackage/releases/tag/V2.0.6.6)
