### ISSUE TITLE
Explo's little ideas

### ISSUE THREAD

**Issue by DjAtomiXx** [HakuSystems/EasyExtractUnitypackage#4]
Since you already know what to do but as reminder so you won't forget:

Custom wallpaper + settings like blur it, darken it or generally setting to make it darker or brighter (like on whatsapp lol)

Extract on R Click a Unitypackage with a shown symbol that let's you extract it without having to open the app itself but still keeps track of the analytics

**Comment by HakuSystems** [comment]
## Noted!

- **Custom Wallpaper with Settings:**
  - Allow users to set custom wallpapers.
  - Include options to adjust the wallpaper settings such as blur, darken, or brighten (similar to WhatsApp).

- **Extract on Right Click:**
  - Implement a feature to extract a Unitypackage directly from a right-click context menu.
  - Display a symbol that indicates the extraction option.
  - Ensure it tracks analytics even without opening the app itself.

**Comment by HakuSystems** [comment]
### V2.0.5.6 Now Includes "Custom Wallpaper" Feature!

i am also actively working on your other suggestions.

**Comment by HakuSystems** [comment]
Both Added in Version: V2.0.5.7
